css_generation_task:
  description: >
    Here is the current HTML document: {file_content}
    Enhance the HTML document given by adding a <style> tag
    containing CSS styles. Use the user's input for theme which is {theme} and color preferences which is {color} to style the document appropriately.
    Ensure the CSS is embedded in the <head> section of the HTML.
  expected_output: >
    An updated HTML document with:
    - A <style> tag inside the <head> section.
    - Styles for body, header, sections, and footer based on the user's theme and color inputs.
    - A cohesive and visually appealing design.
    **Do not generate text before or after the output**.
    **Do not enclose your output in ```html symbols.**
  agent: css_generator